# Generated by Django 5.2.1 on 2025-05-20 03:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='home',
            options={'ordering': ['-created_at'], 'verbose_name': 'Home Listing', 'verbose_name_plural': 'Home Listings'},
        ),
        migrations.AddField(
            model_name='home',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='home',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='home',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload an image of the home', null=True, upload_to='home_images/', verbose_name='Home Image'),
        ),
        migrations.AlterField(
            model_name='home',
            name='title',
            field=models.CharField(help_text='Enter the title for this home listing', max_length=200, verbose_name='Home Title'),
        ),
    ]
